[package]
name = "allocative_derive"
version = "0.2.0"
edition = "2021"
description = "Implementation of derive(Allocative) for allocative crate"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
proc-macro2 = "1.0"
syn = { version = "1.0.27", features = ["extra-traits", "full"] }
